# Generated by Django 3.1.3 on 2020-11-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_auto_20201123_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='expiryDate',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
