# Generated by Django 3.1.3 on 2020-11-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0004_blogdata_expirydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdata',
            old_name='expiryDate',
            new_name='expiryCode',
        ),
    ]
