# Generated by Django 3.1.3 on 2020-11-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0005_auto_20201124_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='perfumeImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
