# Generated by Django 3.1.3 on 2020-11-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0006_blogdata_perfumeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdata',
            name='perfumeImage',
        ),
    ]
