# Generated by Django 3.1.3 on 2020-11-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0007_remove_blogdata_perfumeimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogData',
            new_name='Perfume',
        ),
    ]
